gamedata/lua/lua/shield.lua
credit goes to Balthazar
the current check doesn't work if there is no projectile with the SHIELDPIERCING category in the game
breaks shields when playing LOUD without 4th Dimension since the only projectiles with this category are in the 4th Dimension mod for LOUD
=> fix shielpiercing check

.gitignore, gamedata/LOUD_Mods/mods/LOUD Unit Additions/units/VEB2302/VEB2302_unit.bp
Flayer II buildtime was off, set it to the same as the others.
=> Ignore bat files / Normalize buildTime for Flayer II

gamedata/lua/lua/sim/ScenarioUtilities.lua
Applies the same life time to a unit group spawned as wreckages as any group called 'WRECKAGE' would have.
=> Wreckage lifetime when spawned

gamedata/lua/lua/ui/dialogs/mapselect.lua, gamedata/lua/lua/ui/lobby/lobby.lua
Includes various fixes for map options:
- The default value of an option is chosen if it is not found in previous preferences / game options list-> map options initially show their default value as they are not recorded in the preferences list.
- The default value of a map option is loaded into the map if it wasn't set manually.
- All options have a tooltip that is either loaded in from the string database or from the option table itself. If the option does not have a preference value set (set to '', not nil / removed!) then the tooltips in the option table is used.
- Options have tooltips both in the map select dialog and in the lobby.
Known issues:
- The 'default' value of an option is often not interpreted correctly in the FAF community. In turn, it is often set to the _value_ instead …
=> Map options

gamedata/BlackOps/mods/BlackOpsUnleashed/units/BSB2402/BSB2402_unit.bp, gamedata/BrewLAN_LOUD/mods/BrewLAN_LOUD/units/SEB3303/SEB3303_unit.bp, gamedata/LOUD_Units/mods/LOUD Unit Additions/units/UAB0305/UAB0305_unit.bp, gamedata/LOUD_Units/mods/LOUD Unit Additions/units/UEB0305/UEB0305_unit.bp, gamedata/LOUD_Units/mods/LOUD Unit Additions/units/URB0305/URB0305_unit.bp, gamedata/LOUD_Units/mods/LOUD Unit Additions/units/XSB0305/XSB0305_unit.bp, gamedata/TotalMayhem/mods/TotalMayhem/units/BRMT3AVA/BRMT3AVA_unit.bp, gamedata/lua/lua/victory.lua, gamedata/units/units/UEB5103/UEB5103_unit.bp, gamedata/units/units/URB5103/URB5103_unit.bp, gamedata/units/units/XRL0403/XRL0403_unit.bp
- Remove unitIDs as categories and replace with actual Categories to allow for correct intended functioning of Supremacy VC.
- Add categories as needed in multiple unit BPs to allow for correct intended functioning of Supremacy VC.
=> Supremacy VC Revisited

gamedata/units/units/UEL0301/UEL0301_unit.bp, gamedata/units/units/URL0301/URL0301_unit.bp
- Removed line "MaintenanceConsumptionPerSecondEnergy = 0," from Cybran SACU (url0301) and UEF SACU (uel0301) bp files to correct energy production shown in Quantum Gatway build menu.
=> UNITS - Cybran UEF SACU Energy Prod Descrip Fix

gamedata/BrewLAN_LOUD/mods/BrewLAN_LOUD/units/SRA0313/SRA0313_unit.bp
- Change AutoInitiateAttackCommand to false for the BrewLAN Cybran Twilight Patron T3 Penetration Fighter (sra0313)
=> Aircraft AutoInitiateAttack Update

gamedata/lua/lua/PhxLib.lua, lua_utils/bluePrintExtractor/threatParser_v007.lua
Made a few minor changes to allow lua_utils (command line lua) blue print extractor to work again with Spout's recent changes to PhxLib.
1.) != is not supported in command line lua, change to ~=
2.)  removed use of "continue" as it is not supported in command line lua.  Work around is to return a valid "null" weapDPS object. Now it will skip PhxLib.PhxWeapDPS() but still return a weapon with zero contribution to range, damage, dps, etc. Also, needed to tweak the accumulators so they will work with zero threat.
3.) Updated ThreatParser to v007 so it no longer gags on the use of LOG() and repr() functions.  
4.) Generated a new ..\lua_utils\bluePrintExtractor\LOUD_UnitDB_v007.csv
=> Initial cleanup for lua_utils compatibility

gamedata/lua/lua/ui/game/minimap.lua
- Corrected function for retrieving setting in players .prefs file for viewing minimap resources. The name that was being searched for in the .prefs file was 'minimap_resources' when it should be 'MiniMap_resource_icons'.
=> Minimap Resource Option Fix

gamedata/lua/lua/sim/ScenarioUtilities.lua, gamedata/lua/lua/ui/help/tooltips.lua, gamedata/lua/lua/ui/lobby/lobbyOptions.lua
- Update function looking at unoccupied starting locations to process relocating resources when no AIs are present but lobby option is On.
- Update tooltips.
=> LUA - Relocate Starting Resources Fix

gamedata/units/units/UAS0304/UAS0304_unit.bp, gamedata/units/units/UES0304/UES0304_unit.bp, gamedata/units/units/URS0304/URS0304_unit.bp, gamedata/units/units/XSS0302/XSS0302_unit.bp
- Added/corrected RangeCategory for nuke weapon of T3 Strategic Missile Submarines & Sera T3 Battleship.
- Corrected MaxRadius of nuke subs to match Sera T3 Battleship.
- Removed ProjectileLifetime for nuke weapons to avoid premature detonation in mid-air while missile was en route to target location.
- Units affected:
|--> Aeon Silencer T3 Strategic Missile Submarine (uas0304)
|--> Cybran Plan B T3 Strategic Missile Submarine (urs0304)
|--> Sera Hauthuum T3 Battleship (xss0302)
|--> UEF Ace T3 Strategic Missile Submarine (ues0304)
=> UNITS - Nuke Sub Range Fix

bin/SupComDataPath.lua
- Add line to LOUD Dev init file (SupComDataPath.lua) to load the usermods folder from the LOUD directory. This will allow mod creators to test their mods in the Git-LOUD dev environment without exposing the dev repo to the mods.
=> LOUD Dev init file update - Usermods

gamedata/BlackOps/mods/BlackOpsUnleashed/units/BAB1302/BAB1302_unit.bp, gamedata/BlackOps/mods/BlackOpsUnleashed/units/BSB1302/BSB1302_unit.bp, gamedata/LOUD_Misc/mods/LOUD Integrated Storage/units/BAB1304/BAB1304_unit.bp, gamedata/LOUD_Misc/mods/LOUD Integrated Storage/units/BEB1304/BEB1304_unit.bp, gamedata/LOUD_Misc/mods/LOUD Integrated Storage/units/BRB1304/BRB1304_unit.bp, gamedata/LOUD_Misc/mods/LOUD Integrated Storage/units/BSB1304/BSB1304_unit.bp, gamedata/LOUD_Misc/mods/LOUD Integrated Storage/units/UAB1304/UAB1304_unit.bp, gamedata/LOUD_Misc/mods/LOUD Integrated Storage/units/UEB1304/UEB1304_unit.bp, gamedata/LOUD_Misc/mods/LOUD Integrated Storage/units/URB1304/URB1304_unit.bp, gamedata/LOUD_Misc/mods/LOUD Integrated Storage/units/XSB1304/XSB1304_unit.bp
- Correct UpgradesFrom UnitID for BlackOps Unleashed Aeon & Sera T3 Advanced Hydrocarbon Power Plant to point to T2 UnitID.
- Added UpgradesFromBase UnitIDs to Adv. Hydro & Mass Extractor with Storage bp files of Integrated Storage mod to allow for upgrading all the way from T1 to T3.5.
=> Fix Integrated Storage Hydro & Mex Upgrades

bin/LoudDataPath.lua, bin/SupComDataPath.lua
- Removed line in LOUD Dev init file (SupComDataPath.lua) that told the dev environment to load the units.scd file from the vanilla SCFA install.
- Added line to Dev init to load the extra_env directory added to the repo in June 2022.
- Edited LOUD Dev & Release init files to mirror each other to make future edits easier to follow from one to the other.
=> LOUD Dev and Release Init File Updates

gamedata/LOUD_Misc/mods/SupremeEconomy/hook/lua/ui/game/gamemain.lua, gamedata/LOUD_Misc/mods/SupremeEconomy/hook/lua/ui/game/scoreaccum.lua, gamedata/LOUD_Misc/mods/SupremeEconomy/modules/mciallunits.lua, gamedata/LOUD_Misc/mods/SupremeEconomy/modules/mcibuttons.lua, gamedata/LOUD_Misc/mods/SupremeEconomy/modules/mexes.lua, gamedata/LOUD_Misc/mods/SupremeEconomy/modules/resourceusage.lua
Removed all trailing whitespace
Made unnecessary globals into locals
Cached the UpdateScoreData import
Prevented the UI from becoming unreadable by showing fractional amounts of mass/energy usage
Fixed a possible error where unitWithMostProgress may not be set
=> Supreme Economy cleanup and fixes

gamedata/lua/lua/ui/lobby/lobby.lua
Fixes a bug with how LOUD refreshes the player/AI options in the lobby - although it attempts to refresh them, it does this with the code:
local aitypes = import('/lua/ui/lobby/aitypes.lua').aitypes
which is defined as:
aitypes = import('/lua/enhancedlobby.lua').GetAIList()
However, this doesnt result in GetAIList() being run each time the first line is called, instead it fetches the result from the time the lobby was originally created.
The proposed code removes the reference to aitypes, meaning it now refreshes (e.g. if a player is removed, or if mod options are changed), meaning if custom AI are used, the list of available custom AI gets refreshed at that point, instead of needing the .exe to be restarted.
=> Fix lobby AI option refresh bug

gamedata/lua/lua/aibrain.lua
If non-LOUD AI are being used, LOUD will still try and running certain logic from the event for the brain creation.  This checks for if there are active mods with custom AI present, and (if so) only runs LOUD related logic if the nickname of the brain contains the name of any of the AI listed in the ExtrasAI.lua LOUD file (currently just AI: LOUD).
Testing on a replay with a custom AI and 2 LOUD AI no desync occurred after making this change, but the error message that would previously show was avoided.
Error message for reference:
warning: Error running lua script: ...e\git-loud\gamedata\lua\lua\ai\aiaddbuildertable.lua(56): attempt to call method `AddBuilder' (a nil value)
stack traceback:
...e\git-loud\gamedata\lua\lua\ai\aiaddbuildertable.lua(56): in function `AddGlobalBuilderGroup' …
=> Loud startup error fix

gamedata/LOUD_Misc/mods/LOUD Evenflow Engineers/hook/lua/system/Blueprints.lua
This makes EvenFlow valid Lua 5.1+ so it can be executed by BrewWikiGen, and adds the function that it actually runs: `WikiBlueprints`. It also adds a check before running `oldModBlueprints`, since that'll be nil in that context.
The rest is whitespace changes because Atom is like that.
=> EvenFlow BWG Compatibility

gamedata/lua/lua/aibrain.lua
Supports the score screen appearing where LOUD wins the game against a custom AI
Currently LOUD assumes that all aibrains will have certain values and tries to call methods such as :Destroy() on them.  This adds checks to see if they are nil first before attempting this (to prevent LOUD erroring out if it wins a game).
Tested with and without the changes to confirm that no score screen prompt appeared without changes, but did appear with changes.
=> Brain on death check for nil values

gamedata/lua/lua/options/options.lua, gamedata/lua/lua/ui/help/tooltips.lua
Since the economy bar has been converted to scalability, the reclaim numbers are a fixed component of the bar. If desired, this part can be made optional again. Until then, this PR removes the currently ignored option `GUI: Display Reclaim Window`.
=> Remove obsolete option "GUI: Display Reclaim Window"

gamedata/lua/lua/ui/game/diplomacy.lua, gamedata/lua/lua/ui/game/tabs.lua
In some places in _tabs_ and _diplomacy_ control some numbers were not scaled correctly. The sharing resources sliders in particular should now be in the right place.
=> Fixes some UI glitches with scaling factor not equal to 100%

gamedata/lua/lua/ui/menus/main.lua
When the main menu is displayed, a check is made to ensure that all buttons are visible on the screen. If this is not the case, a dialog is shown with the option to reset the scaling factor to the default value of 100%. This dialog only appears once per game start.
=> Provide assistance with excessive UI scaling

gamedata/lua/lua/maui/grid.lua, gamedata/lua/lua/maui/layouthelpers.lua, gamedata/lua/lua/ui/game/layouts/avatars_mini.lua, gamedata/lua/lua/ui/game/layouts/borders_left.lua, gamedata/lua/lua/ui/game/layouts/borders_mini.lua, gamedata/lua/lua/ui/game/layouts/construction_left.lua, gamedata/lua/lua/ui/game/layouts/construction_mini.lua, gamedata/lua/lua/ui/game/layouts/construction_right.lua, gamedata/lua/lua/ui/game/layouts/controlgroups_mini.lua, gamedata/lua/lua/ui/game/layouts/economy_mini.lua, gamedata/lua/lua/ui/game/layouts/minimap_mini.lua, gamedata/lua/lua/ui/game/layouts/multifunction_mini.lua, gamedata/lua/lua/ui/game/layouts/objectives2_mini.lua, gamedata/lua/lua/ui/game/layouts/orders_left.lua, gamedata/lua/lua/ui/game/layouts/orders_mini.lua, gamedata/lua/lua/ui/game/layouts/orders_right.lua, gamedata/lua/lua/ui/game/layouts/replay_mini.lua, gamedata/lua/lua/ui/game/layouts/score_mini.lua, gamedata/lua/lua/ui/game/layouts/tabs_mini.lua, gamedata/lua/lua/ui/game/layouts/unitviewDetail_left.lua, gamedata/lua/lua/ui/game/layouts/unitviewDetail_mini.lua, gamedata/lua/lua/ui/game/layouts/unitviewDetail_right.lua, gamedata/lua/lua/ui/game/layouts/unitview_left.lua, gamedata/lua/lua/ui/game/layouts/unitview_mini.lua, gamedata/lua/lua/ui/game/layouts/unitview_right.lua, gamedata/lua/lua/ui/game/orders.lua
- Fixed the pause and repeat buttons not being displayed in the construction panel when switching from the enhancements view to the construction view
- Fixed misplacement of buttons in left and right layouts
- Added support for UI scaling in left and right layouts
- Fixed that the edges of the minimap were cut off too much at higher UI scaling factors
- Removed some unused local variables
- Removed some unnecessary spaces
- Replaced some tabs by spaces
- Corrected some carriage return line feeds
=> Fix UI layout issues and some code cleanup

gamedata/lua/lua/utilities.lua
`^` is a bitwise opperation, not power. The function appears unused anyway, but it would've given hilariously wrong values.
=> Fixed and optimised broken unused function

gamedata/lua/lua/ui/dialogs/disconnect.lua, gamedata/lua/lua/ui/dialogs/options.lua, gamedata/lua/lua/ui/dialogs/replay.lua, gamedata/lua/lua/ui/menus/main.lua, gamedata/lua/lua/ui/menus/unitdb.lua, gamedata/lua/lua/ui/uimain.lua
- When starting the game, the main menu now appears immediately instead of a black screen waiting for a mouse click/movement
- Continue to display the LOUD background image in the options, replay and unit database dialogs
- Darken the background for the RestartRequired dialog from the options for better readability similar to the exit dialog
- Fix some UI scaling glitches in main menu and connectivity dialog
- Replace some tabs with spaces, removes some lonely spaces, fix some EOLs
=> Some tiny changes to the UI

gamedata/lua/lua/ui/dialogs/mapselect.lua, gamedata/lua/lua/ui/lobby/lobby.lua
- Fixes a general shift of a few pixels in the display of map positions
- Fixes a downward shift in the display of the map positions for maps `Coastal Conflict` and `Islet`
=> Fixes UI scaling issues with the map positions in lobby & game options

gamedata/lua/lua/options/options.lua, gamedata/lua/lua/ui/menus/main.lua, gamedata/lua/lua/ui/uiutil.lua
Unfortunately, I seem to be the only one who mourns the animations of the main menu from the original game. By chance I stumbled across the code, most of which was just disabled. For what was missing, including the timings, there was the original code. So here it is: The animations of the main menu are back! There is now a well-hidden option at the bottom of the interface options to activate the animations and set their speed. Of course, the animations are disabled by default. Maybe nobody will notice and therefore won't complain about it :)
=> Back to the roots

gamedata/LOUD_Misc/mods/SupremeScoreBoard/hook/lua/ui/game/score.lua, gamedata/lua/lua/maui/window.lua, gamedata/lua/lua/ui/game/chat.lua
- Fixes the double scaling of the minimum chat panel size
- Apply alpha setting also to the scrollbar in chat panel
- Removes the thin gray frame around the chat panel
- Removes the line break in the chat message “sent XXX to YYY” when sharing resources
=> A few small improvements in the chat panel

gamedata/BrewLAN_LOUD/mods/BrewLAN_LOUD/units/SRL0321/SRL0321_unit.bp, gamedata/BrewLAN_LOUD/mods/BrewLAN_LOUD/units/SSL0321/SSL0321_unit.bp, gamedata/WyvernBattlePack/mods/BattlePack/units/WEL0207/WEL0207_unit.bp
* Veteran field removed from Cybran Hedgehog and Seraphim Ythhu: T3 Mobile Strategic Missile Defense (srl0321 and ssl0321) as it's not needed.
* Veteran field removed from UEF Sharp Shooter: T2 Mobile Tactical Missile Defense (wel0207) as it's not needed.
=> mTMD and mSMD Veteran Removal
