LOUD-Project/Git-LOUD

- gamedata/lua/lua/ui/uiutil.lua
changes the default scenario to a map that is available
not sure why the other 2 lines are marked - i just edited the one i changed on the github website inside my browser...
> change default map

- gamedata/LOUD_Misc/mods/ZLOUD Structure Enhancements/hook/lua/ui/help/unitdescription.lua
- gamedata/TotalMayhem/mods/TotalMayhem/hook/lua/ui/help/unitdescription.lua
- Add description for T3 Radar Enhancement on Aeon Mothra, Cybran T3 Air Factory and UEF Blockhouse
- Add description for Shield Enhancement on Aeon Mothra and UEF Blockhouse
> LMISC, TM - Structure Enhancement description additions

- gamedata/4D-CompatabilityPack/mods/4DC/units/URB2306/URB2306_unit.bp
- gamedata/BlackOps/mods/BlackOpsUnleashed/units/BRB2306/BRB2306_unit.bp
- gamedata/BrewLAN_LOUD/mods/BrewLAN_LOUD/units/SAB2308/SAB2308_unit.bp
- gamedata/BrewLAN_LOUD/mods/BrewLAN_LOUD/units/SEB2320/SEB2320_unit.bp
- gamedata/BrewLAN_LOUD/mods/BrewLAN_LOUD/units/SEB2401/SEB2401_unit.bp
- gamedata/BrewLAN_LOUD/mods/BrewLAN_LOUD/units/SRB2402/SRB2402_unit.bp
- gamedata/BrewLAN_LOUD/mods/BrewLAN_LOUD/units/SRB4401/SRB4401_unit.bp
- gamedata/BrewLAN_LOUD/mods/BrewLAN_LOUD/units/SSB2380/SSB2380_unit.bp
- gamedata/LOUD_Units/mods/LOUD Unit Additions/units/LAB2320/lab2320_unit.bp
- gamedata/LOUD_Units/mods/LOUD Unit Additions/units/LEB2320/leb2320_unit.bp
- gamedata/LOUD_Units/mods/LOUD Unit Additions/units/LRB2320/lrb2320_unit.bp
- gamedata/LOUD_Units/mods/LOUD Unit Additions/units/LSB2320/lsb2320_unit.bp
- gamedata/LOUD_Units/mods/LOUD Unit Additions/units/VAB2302/VAB2302_unit.bp
- gamedata/LOUD_Units/mods/LOUD Unit Additions/units/VEB2302/VEB2302_unit.bp
- gamedata/LOUD_Units/mods/LOUD Unit Additions/units/VRB2302/VRB2302_unit.bp
- gamedata/LOUD_Units/mods/LOUD Unit Additions/units/VSB2302/VSB2302_unit.bp
- gamedata/TotalMayhem/mods/TotalMayhem/units/BRMT2PD/BRMT2PD_unit.bp
- gamedata/TotalMayhem/mods/TotalMayhem/units/BRPEXPD/BRPEXPD_unit.bp
- Add or correct RebuildBonusIDs for multiple structures so they can be rebuilt from wrecks.
|--> Details in commits.
> LUNITS, 4D, BLOPS, BL, TM - Rebuilding Bonuses

- gamedata/BlackOps/mods/BlackOpsUnleashed/hook/lua/ui/help/tooltips.lua
- gamedata/BlackOps/mods/BlackOpsUnleashed/units/BRL0401/BRL0401_unit.bp
Correct the description of the Basilisk toggle from Stationary to Siege
> BasiliskSiegeMode

- gamedata/lua/units/Teleport_Rings.bp
- Correct temporary bp file with missing data in AI and Categories sections.
- Remove data for BO ACU units from temporary bp file.
> LUA - Teleport Rings Revised

- .gitignore
- gamedata/BlackOps/mods/BlackopsACUs/units/EAL0001/EAL0001_script.lua
- gamedata/BlackOps/mods/BlackopsACUs/units/EAL0001/EAL0001_unit.bp
- gamedata/BlackOps/mods/BlackopsACUs/units/EEL0001/EEL0001_script.lua
- gamedata/BlackOps/mods/BlackopsACUs/units/EEL0001/EEL0001_unit.bp
- gamedata/BlackOps/mods/BlackopsACUs/units/ERL0001/ERL0001_script.lua
- gamedata/BlackOps/mods/BlackopsACUs/units/ERL0001/ERL0001_unit.bp
- gamedata/BlackOps/mods/BlackopsACUs/units/ESL0001/ESL0001_script.lua
- gamedata/BlackOps/mods/BlackopsACUs/units/ESL0001/ESL0001_unit.bp
- gamedata/lua/lua/AI/aibehaviors.lua
- gamedata/units/units/UAL0304/UAL0304_unit.bp
- gamedata/units/units/UEL0304/UEL0304_unit.bp
- gamedata/units/units/URL0304/URL0304_unit.bp
- gamedata/units/units/XSL0304/XSL0304_unit.bp
- fixed commander runaway behaviour to use total percent when shield is present
- fixed black ops acus weapon upgrades to be properly micromanageable
- fixed t3 mobile arty unpacking
> com totperc, bops com fixes, arty unpack fixes, vs gitignore

- gamedata/BlackOps/mods/BlackopsACUs/hook/lua/ui/help/unitdescription.lua
- gamedata/BlackOps/mods/BlackopsACUs/units/EAL0001/EAL0001_unit.bp
- gamedata/BlackOps/mods/BlackopsACUs/units/EEL0001/EEL0001_unit.bp
- gamedata/BlackOps/mods/BlackopsACUs/units/ERL0001/ERL0001_unit.bp
- gamedata/BlackOps/mods/BlackopsACUs/units/ESL0001/ESL0001_script.lua
- gamedata/BlackOps/mods/BlackopsACUs/units/ESL0001/ESL0001_unit.bp
- gamedata/lua/lua/BlackopsIconSearch.lua
- gamedata/lua/lua/tests/DumpQAVChecklist.lua
- gamedata/lua/lua/ui/game/construction.lua
- gamedata/lua/lua/ui/help/tooltips.lua
- Reorganized enhancement slot sections and individual enhancements to match order of enhancements in _unit.bp files.
- Made some spelling corrections, including those needed in associated files.
- Reworded several descriptions in attempt to provide a better summary or story of the enhancement.
- Rearranged individual enhancement details to fit inline with the description.
- Reworked individual enhancement details so that the value was leading the effected item.
- Added individual enhancement details that were missing.
- Amended individual enhancement details that were incomplete or incorrect.
- Amended bp.Display.Abilities to include LOC tags.
> BOACU - unitdescription Update

- gamedata/lua/lua/sim/ScenarioUtilities.lua
- Revised function for relocating resources at unoccupied starting locations as some maps created with a large starting resource spread weren't being processed correctly.
> LUA - Relocate Starting Resources Fix Redux

- gamedata/TotalMayhem/mods/TotalMayhem/units/BRNT1EXPD/BRNT1EXPD_unit.bp
- Added SATELLITE to TargetRestrictDisallow field of weapons for Mayor T1 Gatling Defense (brnt1expd) to prevent it from targeting satellites.
> TM - Dual Role PD Sat Target Fix

- gamedata/TotalMayhem/mods/TotalMayhem/units/BRPT3BOT/BRPT3BOT_unit.bp
- Removed AutoInitiateAttackCommand line from primary weapon of Total Mayhem Thaam-Thuum T3 Advanced Battle Bot (BRPT3BOT)
> TM Thaam-Thuum AIAC fix

- gamedata/lua/lua/RemoteViewing.lua
This makes the target location ability of things that use this use a 1 second drain event instead of just straight up taking the resources. This means that it no longer fails if you don't have the full amount in storage. It also adds a progress bar while it activates, and doesn't double charge you if you change the target while it's charging.
> Aeon scry cost rework

- gamedata/lua/lua/ui/game/unitview.lua
- Do not display veterancy stats for units of other players
- Do not display duplicate kill stats when max veterancy is reached
- Fixes truncated letters in the player name
> Fixes some issues in unit-view panel

- gamedata/lua/lua/options/options.lua
- gamedata/lua/lua/ui/game/gamemain.lua
- gamedata/lua/lua/ui/help/tooltips.lua
This MR gives you the option of automatically saving the game at a set interval. Added "Auto Save Game" to game options with various intervals to choose from. Three savegames with the names 'AutoSave1', 'AutoSave2' and 'AutoSave3' are created/overwritten in rotation. For non-multiplayer games only.
> Introduce Auto Save Game

- gamedata/lua/lua/ui/game/economy.lua
Fixed some copy'n'paste issues from the original => certain values are now cached correctly.
> Fix broken reclaim values in economy panel

- gamedata/lua/lua/debug/EngineStats.lua
- gamedata/lua/lua/ui/dialogs/console.lua
- Adds UI scaling support for _ShowStats_ and _Console_ panel
- Switched file encoding from _ANSI_(?) to default _UTF-8_
> Additional UI scaling support

- gamedata/lua/lua/ui/dialogs/eschandler.lua
- Now corresponds completely to the FAF version
- Fix escape handler issue
- Terminate the game in a vaguely graceful fashion
> Fix error message `access to nonexistent global variable "yesNoOnly"`

- gamedata/LOUD_Misc/mods/UI-Party/hook/lua/ui/game/avatars.lua
- gamedata/LOUD_Misc/mods/UI-Party/hook/lua/ui/game/borders.lua
- gamedata/LOUD_Misc/mods/UI-Party/hook/lua/ui/game/gamemain.lua
- gamedata/LOUD_Misc/mods/UI-Party/hook/lua/ui/game/layouts/construction_mini.lua
- gamedata/LOUD_Misc/mods/UI-Party/hook/lua/ui/game/layouts/unitviewDetail_mini.lua
- gamedata/LOUD_Misc/mods/UI-Party/hook/lua/ui/game/layouts/unitview_mini.lua
- gamedata/LOUD_Misc/mods/UI-Party/modules/econtrol.lua
- gamedata/LOUD_Misc/mods/UI-Party/modules/settingsUi.lua
- gamedata/LOUD_Misc/mods/UI-Party/modules/ui.lua
- gamedata/LOUD_Misc/mods/UI-Party/modules/unitWatcher.lua
- Fixed display errors in the abilities panel  
- Fixed background size of settings panel
- Fixed saving the correct location of the main panel
> Fix UI scaling issues in mod UI-Party

- gamedata/LOUD_Misc/mods/UI-Party/hook/lua/ui/game/layouts/unitview_mini.lua
- gamedata/LOUD_Misc/mods/UI-Party/modules/unitWatcher.lua
- Fixed abilities panel location
- Fixed malplaced adornment icons
> Fixing further UI-Party mod issues

- gamedata/units/units/UAL0105/UAL0105_unit.bp
- gamedata/units/units/XSS0304/XSS0304_unit.bp
* Removed line for StagingPlatformScanRadius from UAL0105 bp as that overlay is handled in Blueprints.lua
* Add ability tags Personal Stealth and Torpedoes to Sera Yathsou T3 Submarine Hunter
> Base Unit Minor Fixes

- gamedata/units/units/UAB0304/UAB0304_unit.bp
- gamedata/units/units/UEB0304/UEB0304_unit.bp
- gamedata/units/units/URB0304/URB0304_unit.bp
- gamedata/units/units/XSB0304/XSB0304_unit.bp
* Added BuildableCategory to all 4 Quantum Gateways (uab0304, ueb0304, urb0304, xsb0304) to allow them to build the Field Engineers for their respective faction.
> UNITS - Quantum Gateway Field Engineers

- gamedata/BlackOps/mods/BlackOpsUnleashed/units/BRL0205/BRL0205_unit.bp
* Cybran Scorpion T2 Ambush Bot (brl0205)
- Added OVERLAYRADAR to Categories to allow radar ring to be visible.
- Added missing LOC tags to Abilities (for possible future language translation).
> BO Unleashed - Scorpion Fix
